# log frequency
val_check_interval: 5
progress_bar_refresh_rate: 1

wandb:
  name: ${expname}
  project: diffcsp
  entity: null
  log_model: True
  mode: 'online'
  group: ${expname}

wandb_watch:
  log: "parameters"
  log_freq: 0

lr_monitor:
  logging_interval: "step"
  log_momentum: False
