_target_: diffcsp.pl_modules.energy_model.CSPEnergyMatching
time_dim: 256
latent_dim: 0
cost_coord: 1.
cost_lattice: 1.
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
timesteps: 1000
learning_stage: flow
dt: 0.01
langevin_steps: 10
lambda_cd: 1.0



defaults:
  - decoder: scalar_cspnet
  - beta_scheduler: cosine
  - sigma_scheduler: wrapped
