_target_: diffcsp.pl_modules.energy_matching_model.CSPEnergyMatchingT
time_dim: 256
latent_dim: 0
cost_coord: 1.
cost_lattice: 1.
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
timesteps: 1500
flow_timesteps: 1000
learning_stage: flow
dt: 0.01
langevin_steps: 200
lambda_cd: 0.1
flow_warm_epochs: 2000



defaults:
  - decoder: scalar_softcspnet
  - beta_scheduler: cosine
  - flow_beta_scheduler: cosine_flow
  - sigma_scheduler: wrapped
